# Generated by Django 4.2.13 on 2024-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_access_to_cp',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether the user has an access to the control panel.',
                verbose_name='Control panel',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(
                choices=[('ordinary', 'Ordinary'), ('commercial', 'Commercial')], default='ordinary'
            ),
        ),
    ]
