# Generated by Django 4.2.9 on 2024-02-14 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='users',
            field=models.ManyToManyField(through='interactions.PlaylistInteraction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PlaylistsUsersRelation',
        ),
    ]
