# Generated by Django 4.2.9 on 2024-02-17 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('playlists', '0003_change_category_parent_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='category',
        ),
    ]
