# Generated by Django 4.2.9 on 2024-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('playlists', '0005_add_playlist_category_with_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
