# Generated by Django 4.2.9 on 2024-02-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('playlists', '0007_autofill_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playlists.category'),
        ),
    ]
