# Generated by Django 4.2.9 on 2024-02-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('playlists', '0008_alter_category_to_nonullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='privacy_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public'),
        ),
    ]
