# Generated by Django 4.2.9 on 2024-02-26 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('playlists', '0009_exclude_by_link_playlist_privacy_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='status',
            new_name='availability_status',
        ),
    ]
