# Generated by Django 4.2.13 on 2024-07-01 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('playlists', '0013_add_list_ai_suggested_video_pks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLink',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lifetime', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=655)),
                ('hash', models.CharField(db_index=True, max_length=10, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'playlist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='private_links',
                        to='playlists.playlist',
                    ),
                ),
            ],
            options={
                'db_table': 'playlist_private_links',
            },
        ),
    ]
