# Generated by Django 4.2.13 on 2024-07-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('playlists', '0014_add_private_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='privacy_type',
            field=models.CharField(
                choices=[('private', 'Private'), ('public', 'Public'), ('commercial', 'Commercial')], default='public'
            ),
        ),
    ]
