# Generated by Django 4.2.16 on 2024-09-30 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0015_extend_video_and_summarization_models'),
        ('playlists', '0016_add_private_links_for_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTExpensesReport',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_spent', models.IntegerField()),
                (
                    'type_operation',
                    models.CharField(
                        choices=[
                            ('quiz', 'Quiz'),
                            ('transcript', 'Transcript'),
                            ('full_summary', 'Full summary'),
                            ('short_summary', 'Short summary'),
                        ],
                        default='quiz',
                    ),
                ),
                ('api_request', models.CharField(max_length=255)),
                (
                    'playlist',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expenses_reports_for_playlist',
                        to='playlists.playlist',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expenses_reports',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'video',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expenses_reports_for_video',
                        to='videos.video',
                    ),
                ),
                (
                    'video_file',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expenses_reports_for_video_file',
                        to='videos.videofile',
                    ),
                ),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
