# Generated by Django 4.2.9 on 2024-02-12 05:48

import core.conf.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameVideoSet',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='framesets', to='videos.video'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('timestamp_s', models.FloatField()),
                ('image', models.ImageField(storage=core.conf.storage.LocalStorage(), upload_to='frames/')),
                (
                    'frame_set',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='frames.framevideoset'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
