name: Test Server

on:
  push:
    branches:
      - dev

env:
  DOCKER_COMPOSE_FILE: docker-compose.yaml
  HASHTAG: new_dev
  WORK_PATH: /opt/envs/backend

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7.4.0-alpine
        ports:
          - "6379:6379"

    env:
      POETRY_VERSION: 1.2.2
      PYTHON_VERSION: 3.11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create env file
        working-directory: src/core
        run: |
          echo '${{ secrets.REPO_ENV_FILE }}' > .env

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        id: cached-poetry-dependencies
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Install wtpslit
        run: poetry add wtpsplit
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Install packages
        run: poetry run python -m spacy download ru_core_news_sm
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Apply migrations
        run: |
          poetry run python src/manage.py migrate

      - name: Run tests and collect coverage
        run: |
            make test

  build_and_push_to_docker_hub:
    needs: test-lint
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
#        with:
#          token: ${{ secrets.CI_TOKEN }}
#          submodules: true
#      - name: Check out the submodule
#        run: git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra_new/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_ID }}/{{ name }}:${{ github.sha }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
          target: backend

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra_new/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_ID }}/{{ name }}-static:${{ github.sha }}
          cache-from: type=gha,scope=backend-static
          cache-to: type=gha,mode=max,scope=backend-static
          target: static

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Docker login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TESTSERVER }}
          username: ${{ secrets.TESTSERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.REGISTRY_TOKEN }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${{ secrets.REGISTRY }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TESTSERVER }}
          username: ${{ secrets.TESTSERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "infra_new/docker-compose.yaml"
          target: ${{ env.WORK_PATH }}
          strip_components: 1

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        env:
          DOMAIN_NAME: $${{ domain }}
        with:
          host: ${{ secrets.TESTSERVER }}
          username: ${{ secrets.TESTSERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: DOMAIN_NAME
          script: |
            cd ${{ env.WORK_PATH }}
            grep -q COMMIT_SHA .env &&  sed -i -E 's/COMMIT_SHA=[a-z0-9]+/COMMIT_SHA=${{ github.sha }}/g' .env || echo "COMMIT_SHA=${{ github.sha }}" >> .env
            docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d --quiet-pull
            docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} exec -T backend python manage.py migrate
            docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} exec -T backend python manage.py collectstatic --no-input
            docker cp backend:/app/core/collected_static/. /opt/envs/data/backend-static
            docker images prune -a
