# Generated by Django 4.2.8 on 2024-01-09 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("video_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=5000)),
                ("source", models.CharField(choices=[("YOUTUBE", "YouTube"), ("VK", "VK")], default="YOUTUBE")),
                ("origin_link", models.CharField(max_length=500)),
                ("thumbnail_url", models.CharField(max_length=500)),
                ("starts_from", models.IntegerField(default=0)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal"),
                            ("EDUCATIONAL", "Educational"),
                            ("COMMERCIAL", "Commercial"),
                        ],
                        default="PERSONAL",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REMOVED", "Removed"),
                            ("ON_MODERATION", "On moderation"),
                            ("ACTIVE", "Active"),
                            ("BANNED", "Banned"),
                        ],
                        default="ACTIVE",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("users", models.ManyToManyField(related_name="videos", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created"],
                "default_related_name": "videos",
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("data", models.JSONField(null=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transcripts", to="videos.video"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
