# Generated by Django 4.2.9 on 2024-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(
                choices=[('ON_MODERATION', 'On moderation'), ('ACTIVE', 'Active'), ('BANNED', 'Banned')],
                default='ACTIVE',
            ),
        ),
    ]
