# Generated by Django 4.2.9 on 2024-02-25 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0002_drop_removed_video_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploader',
        ),
    ]
