# Generated by Django 4.2.10 on 2024-04-15 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0004_add_is_unavailavble_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(null=True)),
                (
                    'video',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='videos.video'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
