# Generated by Django 4.2.10 on 2024-04-23 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0005_add_quiz_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='timecodes/video/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
