# Generated by Django 4.2.11 on 2024-04-28 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0006_create_video_file_entity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
