# Generated by Django 4.2.11 on 2024-06-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0007_remove_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videofile',
            name='ogg',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
