# Generated by Django 4.2.13 on 2024-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0008_extend_video_file_with_ogg_and_duration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to='videofl/'),
        ),
    ]
