# Generated by Django 4.2.13 on 2024-06-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0009_some'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(max_length=500, upload_to='videofile/'),
        ),
    ]
