# Generated by Django 4.2.13 on 2024-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0010_extend_videofile_file_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcript',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='transcript',
            name='source',
            field=models.CharField(
                choices=[('INTERNAL', 'Internal'), ('ORIGINAL', 'Original'), ('AI', 'AI')],
                db_index=True,
                default='INTERNAL',
            ),
        ),
    ]
