# Generated by Django 4.2.15 on 2024-08-25 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0013_add_transcript_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videofile',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='videofile',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='video_files',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
